/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#bac9cc",
        "secondary-fixed-dim": "#bcc7de",
        "surface-container-high": "#222a3d",
        "primary-fixed-dim": "#00daf3",
        "outline": "#849396",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-container": "#3e495d",
        "surface": "#0b1326",
        "secondary-fixed": "#d8e3fb",
        "on-primary": "#00363d",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-container": "#171f33",
        "surface-container-lowest": "#060e20",
        "on-surface": "#dae2fd",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed": "#e0e3e5",
        "on-secondary-fixed": "#111c2d",
        "surface-container-highest": "#2d3449",
        "on-background": "#dae2fd",
        "inverse-primary": "#006875",
        "secondary": "#bcc7de",
        "on-primary-fixed": "#001f24",
        "inverse-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "on-tertiary-container": "#565a5b",
        "error-container": "#93000a",
        "primary": "#c3f5ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-error-container": "#ffdad6",
        "primary-container": "#00e5ff",
        "primary-fixed": "#9cf0ff",
        "background": "#0b1326",
        "outline-variant": "#3b494c",
        "on-tertiary": "#2d3133",
        "tertiary-container": "#ced1d3",
        "on-secondary": "#263143",
        "on-primary-container": "#00626e",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004f58",
        "inverse-on-surface": "#283044",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        "surface-dim": "#0b1326",
        "tertiary": "#ebedef",
        "on-secondary-container": "#aeb9d0",
        "surface-bright": "#31394d",
        "surface-tint": "#00daf3"
      },
      fontFamily: {
        "headline": ["Newsreader"],
        "body": ["Space Grotesk"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0rem", "lg": "0rem", "xl": "0rem", "full": "9999px"},
    },
  },
  plugins: [],
}
